# Generated by Django 5.1.7 on 2025-03-19 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gutenberg_id', models.IntegerField(unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('cover_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'books_db',
            },
        ),
        migrations.CreateModel(
            name='IndexTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('occurrences', models.IntegerField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.book')),
            ],
            options={
                'db_table': 'index_table',
                'unique_together': {('token', 'book')},
            },
        ),
    ]
