# Generated by Django 5.1.7 on 2025-03-21 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centrality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagerank', models.FloatField()),
                ('closeness', models.FloatField()),
                ('betweenness', models.FloatField()),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='search.book')),
            ],
        ),
    ]
